# SPDX-FileCopyrightText: 2026 Amy Poon <amy@amypoon.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

required_version = "^1.9.0"
style_edition = "2024"

group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
