on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: self-hosted
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak (${{ matrix.name }})
    runs-on: self-hosted
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Development
            profile: development
            manifest: build-aux/com.flufflesamy.AlterEgoTools.Devel.json
            bundle: alter-ego-tools-devel.flatpak
          - name: Release
            profile: release
            manifest: build-aux/com.flufflesamy.AlterEgoTools.json
            bundle: alter-ego-tools.flatpak
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - uses: https://github.com/flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ matrix.bundle }}
          manifest-path: ${{ matrix.manifest }}
          run-tests: true
          cache-key: flatpak-builder-${{ matrix.profile }}-${{ hashFiles('build-aux/**',
            'Cargo.lock') }}
