on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
    - uses: actions/checkout@v6
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: alter-ego-tools.flatpak
        manifest-path: build-aux/com.flufflesamy.AlterEgoTools.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
